// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Footer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<footer class=\"site-footer\"><div class=\"container site-footer__inner\"><div class=\"site-footer__column\"><p class=\"site-footer__title\">каталог</p><ul class=\"site-footer__list\"><li><a href=\"#\" class=\"site-footer__link\">новинки</a></li><li><a href=\"#\" class=\"site-footer__link\">одежда</a></li><li><a href=\"#\" class=\"site-footer__link\">обувь</a></li><li><a href=\"#\" class=\"site-footer__link\">аксессуары</a></li></ul></div><div class=\"site-footer__column\"><p class=\"site-footer__title\">покупателям</p><ul class=\"site-footer__list\"><li><a href=\"#\" class=\"site-footer__link\">оплата и доставка</a></li><li><a href=\"#\" class=\"site-footer__link\">возврат и гарантия</a></li><li><a href=\"#\" class=\"site-footer__link\">вопросы и ответы</a></li><li><a href=\"#\" class=\"site-footer__link\">программа лояльности</a></li></ul></div><div class=\"site-footer__column\"><p class=\"site-footer__title\">о нас</p><ul class=\"site-footer__list\"><li><a href=\"#\" class=\"site-footer__link\">о бренде</a></li><li><a href=\"#\" class=\"site-footer__link\">магазины</a></li><li><a href=\"#\" class=\"site-footer__link\">контакты</a></li><li><a href=\"#\" class=\"site-footer__link\">лукбук</a></li></ul></div></div></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
